### ISSUE TITLE
ctrld ignores config file location (--config) on reboot

### ISSUE THREAD

**Issue by pmcarrion** [Control-D-Inc/ctrld#22] opened 2023-02-13 12:23 UTC
I want ctrld to keep the config file in its own folder instead of the user folder.

I used this command to achieve this:
`sudo ./ctrld start --cd $DID --config /path/to/ctrld/folder/ctrld.toml`

It successfully created the file in the desired folder.

However, upon reboot, ctrld still looks for the config file in the user folder instead of the folder designated above. 

ctrld ignores the config file that is already in its own folder.

To fix this, I have to do the following:

```
sudo ./ctrld service status
Service is running
```

```
sudo ./ctrld service stop
Feb 13 07:12:28.280 ERR resetDNS failed error="exit status 4" prefix=main
Feb 13 07:12:28.280 ERR could not reset DNS error="exit status 4" iface=en7 prefix=main
Feb 13 07:12:28.280 INF Service stopped prefix=main
```

```
sudo ./ctrld service uninstall
Feb 13 07:12:53.111 ERR resetDNS failed error="exit status 4" prefix=main
Feb 13 07:12:53.112 ERR could not reset DNS error="exit status 4" iface=en7 prefix=main
Feb 13 07:12:53.112 INF Service uninstalled prefix=main
```

I could do the command to repeat the creation of the config file in the desired folder, but it will be ignored by ctrld in the next reboot.

So, I'll use this command until this issue is resolved:
```
sudo ./ctrld start --cd $DID
loading config file from: /Users/USER/ctrld.toml
Feb 13 07:13:11.799 INF fetching Controld-D configuration mode=cd prefix=main
Feb 13 07:13:12.771 INF generating ctrld config from Controld-D configuration mode=cd prefix=main
Feb 13 07:13:12.775 INF writing config file to: /Users/USER/ctrld.toml mode=cd prefix=main
Feb 13 07:13:12.846 ERR setDNS failed, ips = ["127.0.0.1"] error="exit status 4" prefix=main
Feb 13 07:13:12.846 ERR could not set DNS for interface error="exit status 4" iface=en7 prefix=main
Feb 13 07:13:12.846 INF Service started prefix=main
```

**Comment by cuonglm** [comment] 2023-02-13 14:56
Hi @pmcarrion, thanks for reporting.

How do you know the config file was ignored? What does `ignore` mean:

 - `ctrld` did not read the config?
 - `ctrld` read the config but the content was overwritten?

**Comment by pmcarrion** [comment] 2023-02-13 16:31
Hi @cuonglm,

None of the above, the config file was in the same folder as the ctrld binary, but ctrld kept looking for the config file on the /Users/USER folder instead of the folder specified when using this command:

`sudo ./ctrld start --cd $DID --config /path/to/ctrld/folder/ctrld.toml`

I rebooted the machine twice to confirm this issue. I was unable to get an Internet connection, and both times I had to do the following:

```
sudo ./ctrld service status
sudo ./ctrld service stop
sudo ./ctrld service uninstall
sudo ./ctrld start --cd $DID --config /path/to/ctrld/folder/ctrld.toml
```

Then I stopped/uninstalled the service and deleted the ctrld.toml file from /path/to/ctrld/folder/.

Finally, I reinstalled the service with this command:
`sudo ./ctrld start --cd $DID`

Since then, ctrld works as expected, reading the config file from its standard location (Users/USER).

**Comment by cuonglm** [comment] 2023-02-13 16:53
@pmcarrion It seems to me that the problem is `ctrld` does not take `--config` into account when `--cd` is specified. To clarify, when you use `--cd`, `ctrld` will always fetch the config and _overwrite_ the content of old config file. It does not attempt to use your old config, even though it does read it.

I'm not sure while you don't get the internet connection after rebooting, would you mind taking a look at the log when this happen? (You can do `--log /path/to/your/log/file` when starting `ctrld`).

**Comment by pmcarrion** [comment] 2023-02-13 18:44
So, instead of using
`sudo ./ctrld start --cd $DID`

I should use
`sudo ./ctrld service start --config /path/to/ctrld/folder/ctrld.toml`

What is the default config file if `--cd` is not used to fetch it?

**Comment by cuonglm** [comment] 2023-02-13 18:59
@pmcarrion Whatever config file you use, `ctrld --cd $DID` will fetch the resolver config, then _overwrite_ the old config content if the config existed, or writing new one if the config is not existed.

The bug here is `ctrld start` does not honor the `--config` file flag, but always find config file in user's home directory. This will be fixed in next release, so when you pass `--config`, `ctrld` will write the configuration to specified file.

**Comment by yegors** [comment] 2023-03-10 20:21
This issue is resolved in the latest release.

**Closed by yegors** 2023-03-10 20:21 UTC
Labels: bug
