### ISSUE TITLE
Issue on UDM pro

### ISSUE THREAD

**Issue by lbouriez** [Control-D-Inc/ctrld#130] opened 2024-01-09 20:20 UTC
Hello, I installed control-d on the UDM pro se and it's working great to identify the clients.
However, since control-d is running, I cannot assign a fixed ip to any devices and get this error message in the UDM: We couldn't apply the gateway configuration changes. Contact support for further assistance.

Are you aware of this, do you know how to fix it ?

Edit: Also, I followed the steps to remove controldD from the UDM (https://docs.controld.com/docs/ctrld#remote-uninstallation)
After restarting, I was able to assign a fixed IP, I then reployed Controld to the router.

**Comment by Hawks-Coccyx** [comment] 2024-01-13 23:34
I can confirm this is happening for me as well. 
Also, I am unable to change port configurations (assign different vlan to a switch-port or disabling a switch-port altogether, for example). I get the same log entry "We couldn't apply the gateway configuration changes. Contact support for further assistance."

Uninstalling ctrld 1.3.3 from UDM Pro resolves the issue.  I am running Network 8.0.26 / UniFi OS 3.2.9

**Comment by yegors** [comment] 2024-01-17 02:42
Hi,

Can you please upgrade to this dev version, there should be a fix for this: https://dl.controld.dev/linux-arm64/ctrld

wget/curl this binary and replace the one on disk in /data/controld and then run `ctrld restart`

**Comment by lbouriez** [comment] 2024-01-17 03:22
I can confirm that the dev version seems to work. When this will be release, is there an auto update of the daemon or do we need to do it ourself?

**Comment by Hawks-Coccyx** [comment] 2024-01-17 03:25
Same here - Played around a little bit with disabling / enabling ports and changing VLANs - seems to work fine now. I will report back if anything changes.

**Comment by Hawks-Coccyx** [comment] 2024-01-17 14:39
Update: Made a change this morning to a VLAN: I just set the network settings back to auto from manual.
 
Immediately after hitting apply, UDM Pro became unresponsive and my SSH connection was dropped (I made the change via the web-interface). Could no longer ping UDM Pro IP. I rebooted it via the LCD screen. Ping came back for a few seconds and then it was gone again. 
I was able to access the Webinterface via external connection and restored a backup and am back up and running without ctrld for the time being.

**Comment by cuonglm** [comment] 2024-01-17 14:45
@Hawks-Coccyx Could you please screenshot what settings did you change?

If you applied the setting without ctrld running, does the problem happen?

**Comment by Hawks-Coccyx** [comment] 2024-01-17 15:16
<img width="1310" alt="Screenshot 2024-01-17 at 07 52 36" src="https://github.com/Control-D-Inc/ctrld/assets/131014704/88fde5de-fccc-4460-804f-43480180125f">

I just finished reinstalling ctrld dev version to test. As of now it allows me to make VLAN changes fine, with it running or stopped, just like last night.  
I will keep toggling these VLAN and port changes over the next days to see if it crashes again after ctrld has been running for a while or perhaps it was a one off...

**Comment by cuonglm** [comment] 2024-01-17 15:18
@Hawks-Coccyx Thanks, it would be surprise, because ctrld does not make any changes related to network/VLAN.

**Comment by yegors** [comment] 2024-01-24 01:10
This issue is resolved in v1.3.4

**Closed by yegors** 2024-01-24 01:10 UTC
