### ISSUE TITLE
[v1.1.0] DNS assignment failed for USB Ethernet dock on MacOS

### ISSUE THREAD

**Issue by pmcarrion** [Control-D-Inc/ctrld#18] opened 2023-02-08 19:37 UTC
Original post: https://feedback.controld.com/posts/1808/ctrld-1-1-auto-config-issues

I'm moving this issue to GitHub per @yegors's request.

Posted by Percy:
> **ctrld_1.1.0_darwin_arm64**
> 
> I used the Auto Config feature, but it didn't work as I expected.
> 
> The README mentions this:
> Once you run the above command, the following things will happen:
> 
> * You resolver configuration will be fetched from the API, and config file templated with the resolver data
> * Application will start as a service, and keep running (even after reboot) until you run the stop or service uninstall sub-commands
> * Your default network interface will be updated to use the listener started by the service
> * All OS DNS queries will be sent to the listener
> 
> However, there are 4 minor issues:
> 
> 1. The auto generated config.toml file is placed in the USER folder instead of the same folder as the ctrld binary.
> 2. ctrld fails to change the DNS server on my computer (listener). See the error below.
> 3. The auto-generated config.toml file only uses DoH. It should include all protocols (DoT, Do3, DoQ).
> 4. ctrld still uses an IPv4 DNS resolver only (76.76.2.0). It should always use IPv4 AND IPv6.
> 
> ```
> sudo ./ctrld start --cd $DID
> loading config file from: /Users/USER/ctrld.toml
> Feb 8 06:59:55.983 INF fetching Controld-D configuration mode=cd prefix=main
> Feb 8 06:59:56.728 INF generating ctrld config from Controld-D configuration mode=cd prefix=main
> Feb 8 06:59:56.730 INF writing config file to: /Users/USER/ctrld.toml mode=cd prefix=main
> Feb 8 06:59:56.800 ERR setDNS failed, ips = ["127.0.0.1"] error="exit status 4" prefix=main
> Feb 8 06:59:56.800 ERR could not set DNS for interface error="exit status 4" iface=en7 prefix=main
> Feb 8 06:59:56.800 INF Service started prefix=main
> ```

Posted by Yegor:
> Hi,
> 
> Firstly, these issues should be reported in the repo: https://github.com/Control-D-Inc/ctrld/issues
> 
> As for the actual report:
> 
> This is expected behavior when running in service mode.
> This is interesting. Can you verify that en7 is in fact the correct interface? Provide output from "service interfaces list" command?
> This is expected behavior. You should use DOH for several reasons (DOT leaks your resolver ID via SNI, DOQ is still highly experimental). You can always edit the config and use whatever you want.
> It only uses this IP to resolve the DNS hostname itself, if not bootstrapped. This is not an issue.

Posted by cuonglm
> @Percy Could you please add -vv to see debug log level? It seems to me ctrld failed to get the service name for your interface en7.

**Comment by pmcarrion** [comment] 2023-02-08 19:39
Hi @yegors

I moved the issue to GitHub.

1. Can I change the config file path? I'd like it to be in the same folder as the binary.

2. Here's the output from `sudo ./ctrld service interfaces list`:
```
Index : 1
Name  : lo0
Addrs : 127.0.0.1/8
        ::1/128
        fe80::1/64
DNS   : 127.0.0.1

Index : 2
Name  : gif0
DNS   : 127.0.0.1

Index : 3
Name  : stf0
DNS   : 127.0.0.1

Index : 4
Name  : anpi2
Addrs : fe80::d8e4:19ff:feca:d930/64
DNS   : 127.0.0.1

Index : 5
Name  : anpi1
Addrs : fe80::d8e4:19ff:feca:d92f/64
DNS   : 127.0.0.1

Index : 6
Name  : anpi0
Addrs : fe80::d8e4:19ff:feca:d92e/64
DNS   : 127.0.0.1

Index : 7
Name  : en4
DNS   : 127.0.0.1

Index : 8
Name  : en5
DNS   : 127.0.0.1

Index : 9
Name  : en6
DNS   : 127.0.0.1

Index : 10
Name  : en1
DNS   : 127.0.0.1

Index : 11
Name  : en2
DNS   : 127.0.0.1

Index : 12
Name  : en3
DNS   : 127.0.0.1

Index : 14
Name  : bridge0
DNS   : 127.0.0.1

Index : 15
Name  : ap1
Addrs : fe80::f4d4:88ff:fe5d:aa8f/64
DNS   : 127.0.0.1

Index : 16
Name  : en0
DNS   : 127.0.0.1

Index : 17
Name  : awdl0
Addrs : fe80::5c97:42ff:fe52:c3b2/64
DNS   : 127.0.0.1

Index : 18
Name  : llw0
Addrs : fe80::5c97:42ff:fe52:c3b2/64
DNS   : 127.0.0.1

Index : 19
Name  : utun0
Addrs : fe80::36d2:fd7b:ddcb:d72a/64
DNS   : 127.0.0.1

Index : 20
Name  : utun1
Addrs : fe80::552:d138:9fcd:6929/64
DNS   : 127.0.0.1

Index : 21
Name  : utun2
Addrs : fe80::ce81:b1c:bd2c:69e/64
DNS   : 127.0.0.1

Index : 22
Name  : utun3
DNS   : 127.0.0.1

Index : 23
Name  : utun4
Addrs : fe80::dda2:59b9:3122:e5b0/64
DNS   : 127.0.0.1

Index : 24
Name  : utun5
Addrs : fe80::c8ea:c986:ee89:7530/64
DNS   : 127.0.0.1

Index : 25
Name  : utun6
Addrs : fe80::653c:9d17:5716:2091/64
DNS   : 127.0.0.1

Index : 26
Name  : utun7
Addrs : fe80::1bdb:2c9d:8d42:220/64
DNS   : 127.0.0.1

Index : 27
Name  : utun8
Addrs : fe80::40e0:4256:1401:3e5f/64
DNS   : 127.0.0.1

Index : 28
Name  : utun9
Addrs : fe80::d010:32c9:e4d1:a9d/64
DNS   : 127.0.0.1

Index : 29
Name  : utun10
Addrs : fe80::26c2:1f73:f94e:f11a/64
DNS   : 127.0.0.1

Index : 13
Name  : en7
Addrs : fe80::485:152e:55ad:4879/64
        192.168.50.30/24
        2001:1388:3c0:70ae:18c1:4c4d:39db:5124/64
        2001:1388:3c0:70ae:d523:9365:f598:be7a/64
DNS   : 127.0.0.1

```
3. Thanks for explaining. I'll stick to using Do3 and DoH.

4. I know, but what happens when the ISP only provides IPv6 addresses? My ISP has an IPv6-only beta test, and I had to opt out because ctrld insisted in using an IPv4 address on an IPv6-only network.

**Comment by yegors** [comment] 2023-02-08 19:49
1. You can specify the config location using a --config flag https://github.com/Control-D-Inc/ctrld/blob/main/docs/ephemeral_mode.md
2. Hmm, that looks really puzzling, looks like DNS got configured on all your in interfaces. What exact command did you use to do this? You can hide your actual resolver ID. 
3. N/A
4. It's very doubtful you don't have any IPv4 connectivity, as that would render most of the Internet unreachable. Can you ping 76.76.2.0?

**Comment by pmcarrion** [comment] 2023-02-08 19:51
Hi @cuonglm

I get this error when using this command: `sudo ./ctrld service start  -vv`
`2023/02/08 14:49:14 failed to decode config file: While parsing config: toml: table 0 already exists`

**Comment by yegors** [comment] 2023-02-08 19:55
Your config is invalid, you used `network.0` or `listiner.0` or `upstream.0` multiple times.

**Comment by pmcarrion** [comment] 2023-02-08 20:07
2. I manually configured the DNS to 127.0.0.1 on all interfaces after I saw the error. I couldn't get an Internet connection until l did that.
This is the command I used: `sudo ./ctrld start --cd $DID`

4. I can, now that I'm out of my ISP's IPv6-only beta test.
I was unable to ping IPv4 addresses while on the beta test.

> Your config is invalid, you used `network.0` or `listiner.0` or `upstream.0` multiple times. Should probably make this error more descriptive and say what exactly is duplicated. @cuonglm

I corrected the error. There were 2 'upstream.0'

Here's the result from the command @cuonglm requested:
```
sudo ./ctrld service start  -vv
loading config file from: /Users/USER/ctrld.toml
Feb  8 15:00:52.342 INF Service started prefix=main
```
But there's no debug log.

**Comment by yegors** [comment] 2023-02-08 20:13
2. Hmm, then this data is not very helpful. We would need to see the state after the error. Setting DNS on all your interfaces like this is not a good idea, you should only do it on `en7` which is your NIC. 

Can you undo what you did on all interfaces, then run 

`stop` command and `service uninstall`. 

Make sure everything is working normally, and then re-do the setup with this flag:

`start --cd $DID`

See if you get the same error, and if so, provide output from `service interfaces list` command. Then `dig verify.controld.com` AND `dig verify.controld.com @127.0.0.1` and provide those outputs as well.

**Comment by yegors** [comment] 2023-02-08 20:15
Also, if the above fails, then try this command: `service start --cd $DID --iface en7`

**Comment by pmcarrion** [comment] 2023-02-08 20:34
I removed 127.0.0.1 from all interfaces.

```
sudo ./ctrld stop
Feb  8 15:25:46.205 ERR resetDNS failed error="exit status 4" prefix=main
Feb  8 15:25:46.205 ERR could not reset DNS error="exit status 4" iface=en7 prefix=main
Feb  8 15:25:46.205 INF Service stopped prefix=main
```

```
sudo ./ctrld service uninstall
Feb  8 15:26:24.995 ERR resetDNS failed error="exit status 4" prefix=main
Feb  8 15:26:24.995 ERR could not reset DNS error="exit status 4" iface=en7 prefix=main
Feb  8 15:26:24.995 INF Service uninstalled prefix=main
```

```
sudo ./ctrld start --cd $DID
loading config file from: /Users/pmcarrion/ctrld.toml
Feb  8 15:26:57.339 INF fetching Controld-D configuration mode=cd prefix=main
Feb  8 15:26:58.048 INF generating ctrld config from Controld-D configuration mode=cd prefix=main
Feb  8 15:26:58.050 INF writing config file to: /Users/pmcarrion/ctrld.toml mode=cd prefix=main
Feb  8 15:26:58.127 ERR setDNS failed, ips = ["127.0.0.1"] error="exit status 4" prefix=main
Feb  8 15:26:58.127 ERR could not set DNS for interface error="exit status 4" iface=en7 prefix=main
Feb  8 15:26:58.127 INF Service started prefix=main
```

```
sudo ./ctrld service interfaces list
Index : 1
Name  : lo0
Addrs : 127.0.0.1/8
        ::1/128
        fe80::1/64
DNS   : 2001:1388:3c0:70ae::1
      : 192.168.50.1

Index : 2
Name  : gif0
DNS   : 2001:1388:3c0:70ae::1
      : 192.168.50.1

Index : 3
Name  : stf0
DNS   : 2001:1388:3c0:70ae::1
      : 192.168.50.1

Index : 4
Name  : anpi2
Addrs : fe80::d8e4:19ff:feca:d930/64
DNS   : 2001:1388:3c0:70ae::1
      : 192.168.50.1

Index : 5
Name  : anpi1
Addrs : fe80::d8e4:19ff:feca:d92f/64
DNS   : 2001:1388:3c0:70ae::1
      : 192.168.50.1

Index : 6
Name  : anpi0
Addrs : fe80::d8e4:19ff:feca:d92e/64
DNS   : 2001:1388:3c0:70ae::1
      : 192.168.50.1

Index : 7
Name  : en4
DNS   : 2001:1388:3c0:70ae::1
      : 192.168.50.1

Index : 8
Name  : en5
DNS   : 2001:1388:3c0:70ae::1
      : 192.168.50.1

Index : 9
Name  : en6
DNS   : 2001:1388:3c0:70ae::1
      : 192.168.50.1

Index : 10
Name  : en1
DNS   : 2001:1388:3c0:70ae::1
      : 192.168.50.1

Index : 11
Name  : en2
DNS   : 2001:1388:3c0:70ae::1
      : 192.168.50.1

Index : 12
Name  : en3
DNS   : 2001:1388:3c0:70ae::1
      : 192.168.50.1

Index : 14
Name  : bridge0
DNS   : 2001:1388:3c0:70ae::1
      : 192.168.50.1

Index : 15
Name  : ap1
Addrs : fe80::f4d4:88ff:fe5d:aa8f/64
DNS   : 2001:1388:3c0:70ae::1
      : 192.168.50.1

Index : 16
Name  : en0
DNS   : 2001:1388:3c0:70ae::1
      : 192.168.50.1

Index : 17
Name  : awdl0
Addrs : fe80::5c97:42ff:fe52:c3b2/64
DNS   : 2001:1388:3c0:70ae::1
      : 192.168.50.1

Index : 18
Name  : llw0
Addrs : fe80::5c97:42ff:fe52:c3b2/64
DNS   : 2001:1388:3c0:70ae::1
      : 192.168.50.1

Index : 19
Name  : utun0
Addrs : fe80::36d2:fd7b:ddcb:d72a/64
DNS   : 2001:1388:3c0:70ae::1
      : 192.168.50.1

Index : 20
Name  : utun1
Addrs : fe80::552:d138:9fcd:6929/64
DNS   : 2001:1388:3c0:70ae::1
      : 192.168.50.1

Index : 21
Name  : utun2
Addrs : fe80::ce81:b1c:bd2c:69e/64
DNS   : 2001:1388:3c0:70ae::1
      : 192.168.50.1

Index : 22
Name  : utun3
DNS   : 2001:1388:3c0:70ae::1
      : 192.168.50.1

Index : 23
Name  : utun4
Addrs : fe80::dda2:59b9:3122:e5b0/64
DNS   : 2001:1388:3c0:70ae::1
      : 192.168.50.1

Index : 24
Name  : utun5
Addrs : fe80::c8ea:c986:ee89:7530/64
DNS   : 2001:1388:3c0:70ae::1
      : 192.168.50.1

Index : 25
Name  : utun6
Addrs : fe80::653c:9d17:5716:2091/64
DNS   : 2001:1388:3c0:70ae::1
      : 192.168.50.1

Index : 26
Name  : utun7
Addrs : fe80::1bdb:2c9d:8d42:220/64
DNS   : 2001:1388:3c0:70ae::1
      : 192.168.50.1

Index : 27
Name  : utun8
Addrs : fe80::40e0:4256:1401:3e5f/64
DNS   : 2001:1388:3c0:70ae::1
      : 192.168.50.1

Index : 28
Name  : utun9
Addrs : fe80::d010:32c9:e4d1:a9d/64
DNS   : 2001:1388:3c0:70ae::1
      : 192.168.50.1

Index : 29
Name  : utun10
Addrs : fe80::26c2:1f73:f94e:f11a/64
DNS   : 2001:1388:3c0:70ae::1
      : 192.168.50.1

Index : 13
Name  : en7
Addrs : fe80::485:152e:55ad:4879/64
        192.168.50.30/24
        2001:1388:3c0:70ae:18c1:4c4d:39db:5124/64
        2001:1388:3c0:70ae:d523:9365:f598:be7a/64
DNS   : 2001:1388:3c0:70ae::1
      : 192.168.50.1
```

```
dig verify.controld.com

; <<>> DiG 9.10.6 <<>> verify.controld.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 54787
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;verify.controld.com.		IN	A

;; ANSWER SECTION:
verify.controld.com.	20	IN	CNAME	api.controld.com.
api.controld.com.	300	IN	A	147.185.34.1

;; Query time: 16 msec
;; SERVER: 192.168.50.1#53(192.168.50.1)
;; WHEN: Wed Feb 08 15:28:08 -05 2023
;; MSG SIZE  rcvd: 71
```

```
dig verify.controld.com @127.0.0.1

; <<>> DiG 9.10.6 <<>> verify.controld.com @127.0.0.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 11499
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;verify.controld.com.		IN	A

;; ANSWER SECTION:
verify.controld.com.	20	IN	CNAME	api.controld.com.
api.controld.com.	273	IN	A	147.185.34.1

;; Query time: 42 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Wed Feb 08 15:28:35 -05 2023
;; MSG SIZE  rcvd: 118
```

**Comment by pmcarrion** [comment] 2023-02-08 20:37
```
sudo ./ctrld service start --cd $DID --iface en7
loading config file from: /Users/USER/ctrld.toml
Feb  8 15:36:45.321 INF fetching Controld-D configuration mode=cd prefix=main
Feb  8 15:36:46.040 INF generating ctrld config from Controld-D configuration mode=cd prefix=main
Feb  8 15:36:46.042 INF writing config file to: /Users/USER/ctrld.toml mode=cd prefix=main
Feb  8 15:36:46.107 ERR setDNS failed, ips = ["127.0.0.1"] error="exit status 4" prefix=main
Feb  8 15:36:46.107 ERR could not set DNS for interface error="exit status 4" iface=en7 prefix=main
Feb  8 15:36:46.107 INF Service started prefix=main
```

**Comment by pmcarrion** [comment] 2023-02-08 20:44
My computer appears to be using the router's $DID.
I manually set my NIC (en7) to use 127.0.0.1 as the DNS resolver again.

**Comment by yegors** [comment] 2023-02-08 21:30
What MacOS version are you running?

**Comment by pmcarrion** [comment] 2023-02-08 21:36
macOS Ventura 13.2 (22D49)

**Comment by cuonglm** [comment] 2023-02-09 00:28
@pmcarrion What's the status of `networksetup -listservicenetworkorder`?

**Comment by pmcarrion** [comment] 2023-02-09 01:30
```
networksetup -listnetworkserviceorder
An asterisk (*) denotes that a network service is disabled.
(1) USB 10/100/1000 LAN (Dock)
(Hardware Port: USB 10/100/1000 LAN, Device: en7)

(2) USB 10/100/1000 LAN 2 (Uni)
(Hardware Port: USB 10/100/1000 LAN, Device: en8)

(3) Wi-Fi
(Hardware Port: Wi-Fi, Device: en0)

(4) iPhone USB
(Hardware Port: iPhone USB, Device: en9)

(5) Thunderbolt Bridge
(Hardware Port: Thunderbolt Bridge, Device: bridge0)
```

**Comment by yegors** [comment] 2023-02-09 01:51
Hmm, very interesting. Seems like its detecting the wrong interface (en7) when your Wifi NIC (which I assume you use?) is en0. 

if so, can you stop/uninstall service and re-run with `service start --cd $DID --iface en0`

Does it start normally with no errors?

**Comment by pmcarrion** [comment] 2023-02-09 01:59
This is the interface I'm using right now, as I always prefer to use Ethernet if available.
```
(1) USB 10/100/1000 LAN (Dock)
(Hardware Port: USB 10/100/1000 LAN, Device: en7)
```

I only use Wi-Fi when there's no Ethernet connection.

**Comment by yegors** [comment] 2023-02-09 02:11
Can you provide the model of your Ethernet adapter? Seems like setting DNS on it fails in a non-standard way. 

Also, as a sanity check, can you unplug it, switch to Wifi, stop/uninstall service and re-run `start --cd $DID`. It should attempt to use en0, and hopefully succeed.

**Comment by pmcarrion** [comment] 2023-02-09 03:08
This is the Dock I'm using: https://eshop.macsales.com/shop/owc-thunderbolt-dock

From System Information - Ethernet:
```
USB 10/100/1000 LAN:

  Bus:	USB
  Vendor Name:	Realtek
  Product Name:	USB 10/100/1000 LAN
  Vendor ID:	0x0bda
  Product ID:	0x8153
  USB Link Speed:	Up to 5 Gb/s
  Driver:	com.apple.DriverKit.AppleUserECM
  BSD Device Name:	en7
  MAC Address:	00:23:a4:XX:XX:XX
  AVB Support:	No
```

It works as expected on Wi-Fi (en0) and changes the DNS server to 127.0.0.1 automatically:
```
sudo ./ctrld start --cd $DID
Feb  8 22:01:55.825 INF fetching Controld-D configuration mode=cd prefix=main
Feb  8 22:01:56.594 INF generating ctrld config from Controld-D configuration mode=cd prefix=main
Feb  8 22:01:56.596 INF writing config file to: /Users/USER/ctrld.toml mode=cd prefix=main
Feb  8 22:01:56.654 INF Service started prefix=main
```

It seems ctrld needs to be tweaked for unconventional interfaces, such as the OWC Thunderbolt Dock.

**Comment by yegors** [comment] 2023-02-09 03:29
Thanks, this helps. We'll try to reproduce this issue.

**Comment by pmcarrion** [comment] 2023-02-09 11:53
I changed my connection back to Ethernet after testing on Wi-Fi only, but ctrld is still unable to reset the DNS for the Ethernet Dock (`en7`).
However, it successfully changed the DNS for `en7` while using `en0` (Wi-Fi) with the Dock connected to the computer and the Ethernet cable unplugged from the Dock.

```
sudo ./ctrld stop
Feb  9 06:01:01.903 ERR resetDNS failed error="exit status 4" prefix=main
Feb  9 06:01:01.903 ERR could not reset DNS error="exit status 4" iface=en7 prefix=main
Feb  9 06:01:01.903 INF Service stopped prefix=main
```

```
sudo ./ctrld service uninstall
Feb  9 06:01:07.506 ERR resetDNS failed error="exit status 4" prefix=main
Feb  9 06:01:07.506 ERR could not reset DNS error="exit status 4" iface=en7 prefix=main
Feb  9 06:01:07.506 INF Service uninstalled prefix=main
```

I executed the `run --config` command, and it seems to be working as expected. 
Also, my ISP re-enabled the IPv6-only beta test during the night and I noticed ctrld now has an IPv6 bootstrap IP. I turned off the IPv6-only beta test for now, as macOS was failing to ping some IPv4 addresses.
```
sudo ./ctrld run --config /Users/USER/CLI-Apps/ctrld_1.1.0_darwin_arm64/ctrld.toml
loading config file from: /Users/USER/CLI-Apps/ctrld_1.1.0_darwin_arm64/ctrld.toml
Feb  9 06:03:34.503 INF Service started prefix=main
Feb  9 06:03:34.618 INF Setting bootstrap IP for upstream.0 bootstrap_ip=2606:1a40::22 prefix=main
Feb  9 06:03:35.480 INF Starting DNS server on listener.0: 127.0.0.1:53 prefix=main
^CFeb  9 06:05:00.457 INF Service stopped prefix=main
```
ctrld uses the desired file path now when using the command `start --cd $DID`, but I noticed it still recreates the ctrld.toml file on the home folder. Both ctrld.toml files are identical.

```
sudo ./ctrld start --cd $DID
loading config file from: /Users/USER/CLI-Apps/ctrld_1.1.0_darwin_arm64/ctrld.toml
Feb  9 06:07:35.221 INF fetching Controld-D configuration mode=cd prefix=main
Feb  9 06:07:35.985 INF generating ctrld config from Controld-D configuration mode=cd prefix=main
Feb  9 06:07:35.988 INF writing config file to: /Users/USER/CLI-Apps/ctrld_1.1.0_darwin_arm64/ctrld.toml mode=cd prefix=main
Feb  9 06:07:36.058 ERR setDNS failed, ips = ["127.0.0.1"] error="exit status 4" prefix=main
Feb  9 06:07:36.058 ERR could not set DNS for interface error="exit status 4" iface=en7 prefix=main
Feb  9 06:07:36.058 INF Service started prefix=main
```

**Comment by yegors** [comment] 2023-02-10 18:31
We just tested it with another USB Ethernet adapter, unable to reproduce your issue. Could be a vendor specific issue, as you're on Realtek, and we tested with Belkin. 

In the mean time, you can just manually configure the listener on the NIC while we dig deeper.

**Comment by pmcarrion** [comment] 2023-02-10 21:38
This is actually a Thunderbolt 4 Dock with several built-in interfaces, not just a USB Ethernet adapter. Perhaps that's the issue?

I've already set the DNS server manually.

**Comment by yegors** [comment] 2023-02-13 21:39
We partially reproduced the issue, not the same error as you have, but the same net effect. Only seems to happen with some USB/Thunderbolt docs/hubs, but not all. This suggests some hardware specific issue/fault.

**Comment by yegors** [comment] 2023-03-10 20:21
This issue is resolved in the latest release.

**Closed by yegors** 2023-03-10 20:21 UTC
Labels: bug, MacOS
